### ISSUE TITLE
Add link to original repo

### ISSUE THREAD

**Issue by kekru** [fernandodebrando/docker-remote-api-tls#2]
Hi,  
great, that you like my code :)  
Due to the original license, you should add the original license text.  
See https://github.com/kekru/docker-remote-api-tls/blob/master/LICENSE  

It would also be nice if you add a link to my original repo https://github.com/kekru/docker-remote-api-tls  

Happy New Year
Kevin

**Comment by fernandodebrando** [comment]
Hi,
yes, great solution.

Sorry about anything, I just forgot to add the reference. Initially I thought I had a fork, so I ended up not paying attention to it.
Just added, please check and anything let me know.

Thanks!

Happy New Year
Fernando

**Comment by kekru** [comment]
Thank you, looks good!
