### ISSUE TITLE
Questionamentos das funcionalidades e segurança

### ISSUE THREAD

**Issue by pedroricardo** [fernandodebrando/docker-remote-api-tls#4]
É possível iniciar, criar, deletar e coletar métricas de containers hospedados em outras VPS por exemplo de forma segura através dessa Api ?

Qual a chance de ao usar essa solução eu abrir vulnerabilidade em meu servidor?

**Comment by fernandodebrando** [comment]
Sim @pedroricardo, habilitando a API desta forma você garante que somente com autenticação consiga ter acesso.

**Comment by pedroricardo** [comment]
Outra duvida amigo como eu posso usar o docker-compose e essa api?

por exemplo executar uma aplicação com docker-compose em um servidor externo via docker-remote-api-tls?

**Comment by fernandodebrando** [comment]
Acredito que este artigo pode te ajudar https://www.docker.com/blog/how-to-deploy-on-remote-docker-hosts-with-docker-compose/.
